# Generated by Django 4.0.5 on 2022-06-16 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mascotas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mascota',
            name='raza',
        ),
        migrations.AddField(
            model_name='mascota',
            name='tipo_animal',
            field=models.CharField(choices=[('Desconocido', 'Desconocido'), ('Pajaro', 'Pajaro'), ('Gato', 'Gato'), ('Perro', 'Perro'), ('Conejo', 'Conejo'), ('Huron', 'Huron'), ('Reptil', 'Reptil'), ('Otro', 'Otro')], default='Sin categoria', max_length=20),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='domicilio',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='edad',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
